### PR TITLE
Simplified syntax as Python 2 is unsupported

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by josiasmontag** [comment]
Python 2.7 is supported.

**Comment by claudep** [comment]
I thought it was unsupported because of `setup.py`: "Programming Language :: Python :: 3"

Does it make sense to still support Python 2, which is now unsupported by Python maintainers?

**Comment by josiasmontag** [comment]
We still have some customers that are stuck with Python 2.7 and therefore we would like to keep support as long as possible.

**Comment by claudep** [comment]
I see, that makes sense. Feel free to reuse the patch when you'll drop Python 2.

**Comment by josiasmontag** [comment]
Yea, thanks for your patch anyways!

**Pull request closed without merging**
